spring:
  application:
    name: alert-service
  config:
    import: "optional:configserver:http://config-server:8888/"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka