services:

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - app-net

  config-server:
    build: ./config-server
    container_name: config-server
    depends_on:
      - discovery-service
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/app/config-repo
    networks:
      - app-net

  translation-service:
    build: ./translation-service
    container_name: translation-service
    ports:
      - "5001:5001"
    networks:
      - app-net

  nlp-service:
    build: ./nlp-service
    container_name: nlp-service
    ports:
      - "5000:5000"
    networks:
      - app-net

  incident-db:
    image: mysql:8.4
    container_name: incident-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: incident_db
    ports:
      - "3307:3306"
    volumes:
      - incident-db-data:/var/lib/mysql
    networks:
      - app-net

  incident-service:
    build: ./incident-service
    container_name: incident-service
    depends_on:
      - incident-db
      - config-server
      - discovery-service
      - translation-service
      - nlp-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888/"
    restart: always
    ports:
      - "8081:8081"
    networks:
      - app-net

  user-db:
    image: mysql:8.4
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3308:3306"
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - app-net

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - user-db
      - config-server
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888/"
    restart: always
    ports:
      - "8082:8082"
    networks:
      - app-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - config-server
      - discovery-service
      - user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888/"
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000
    restart: always
    ports:
      - "8083:8083"
    networks:
      - app-net

  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    depends_on:
      - config-server
      - discovery-service
      - incident-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888/"
    restart: always
    ports:
      - "8084:8084"
    networks:
      - app-net

  alert-db:
    image: mysql:8.4
    container_name: alert-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alert_db
    ports:
      - "3309:3306"    
    volumes:
      - alert-db-data:/var/lib/mysql
    networks:
      - app-net

  alert-service:
    build: ./alert-service
    container_name: alert-service
    depends_on:
      - alert-db
      - config-server
      - discovery-service
      - incident-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888/"
    restart: always
    ports:
      - "8085:8085"
    networks:
      - app-net

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    depends_on:
      - config-server
      - discovery-service
      - incident-service
      - user-service
      - auth-service
      - analytics-service
      - alert-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_FAIL_FAST: "false"
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888/"
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-net

  
  frontend:
    build: ../frontend
    container_name: frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: npm start
    networks:
      - app-net
    depends_on:
      - gateway-service


networks:
  app-net:

volumes:
  incident-db-data:
  user-db-data:
  alert-db-data: